# Generated by Django 3.2.25 on 2024-10-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aTravel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloginfo',
            options={'managed': False, 'verbose_name': '攻略信息', 'verbose_name_plural': '攻略信息'},
        ),
        migrations.AlterModelOptions(
            name='foodinfo',
            options={'managed': False, 'verbose_name': '美食信息', 'verbose_name_plural': '美食信息'},
        ),
        migrations.AlterModelOptions(
            name='historyinfo',
            options={'managed': False, 'verbose_name': '历史规划', 'verbose_name_plural': '历史规划'},
        ),
        migrations.AlterModelOptions(
            name='hotleinfo',
            options={'managed': False, 'verbose_name': '酒店信息', 'verbose_name_plural': '酒店信息'},
        ),
        migrations.AlterModelOptions(
            name='jdinfo',
            options={'managed': False, 'verbose_name': '景点信息', 'verbose_name_plural': '景点信息'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': False, 'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
